pub mod adapter;
pub mod assemble;
mod base64;
pub mod churn;
pub mod cleanup;
pub mod conversion;
pub mod density;
pub mod directional;
pub mod flipbook;
pub mod format_study;
pub mod fusion;
pub mod kit;
pub mod kit_bake;
mod mesh_resource_cache;
pub mod model;
pub mod pose;
pub mod posed;
pub mod project;
pub mod provider_pin;
pub mod quality;
pub mod runtime;
mod studio_playback;
pub mod surface;
pub mod surface_evidence;
pub mod temporal;
pub mod video_motion;

pub const DEFAULT_PROJECT_FILE: &str = "content/projects/voxel-lab.project.json";
